### ISSUE TITLE
pyqt 4 Slip-rate calculator

### ISSUE THREAD

**Issue by ghost** [cossatot/slip_rate_calculator#18]
HI! I am on a Windows system and I downloaded Anaconda3 and tried to complete the first part of your instructions. Would you mind advising me on how to resolve the problem I am running into? I apologize if the solution is trivial! I have never used Anaconda and am not super familiar with python. I also sent an email, but wasn't sure if it was the correct address.

The issue arises when trying to set up the environment. Here is the error:

```
conda env create -f slip_rate_calculator_env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
 pyqt=4
```

When trying to install pyqt4 separately, It provides the following error:

```
conda install pyqt=4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve._

PackagesNotFoundError: The following packages are not available from current channels:_

  - pyqt=4

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to https://anaconda.org/

and use the search bar at the top of the page.
```

Do you have any recommendations on what to do here?

**Comment by ghost** [comment]
Ok, So I found that the environment is created when I use the following command
`conda config --set restore_free_channel true`
However when I try to activate the environment I receive another error:
```
python SlipRateGUI.pyw
Traceback (most recent call last):
  File "SlipRateGUI.pyw", line 8, in <module>
    from qtconsole.rich_ipython_widget import RichIPythonWidget
  File "/home/50b488c8-bc0c-4f33-a595-9db23a04026a/.conda/envs/slip_rate_calculator/lib/python3.5/site-packages/qtconsole/rich_ipython_widget.py", line 4, in <module>
    from .rich_jupyter_widget import *
  File "/home/50b488c8-bc0c-4f33-a595-9db23a04026a/.conda/envs/slip_rate_calculator/lib/python3.5/site-packages/qtconsole/rich_jupyter_widget.py", line 9, in <module>
    from qtpy import QtCore, QtGui, QtWidgets
  File "/home/50b488c8-bc0c-4f33-a595-9db23a04026a/.conda/envs/slip_rate_calculator/lib/python3.5/site-packages/qtpy/__init__.py", line 237, in <module>
    from . import QtDataVisualization as QtDatavisualization
  File "/home/50b488c8-bc0c-4f33-a595-9db23a04026a/.conda/envs/slip_rate_calculator/lib/python3.5/site-packages/qtpy/QtDataVisualization.py", line 22, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```
